menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Talks', url: '/talks'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

talks:
- {name: 'Mathematical Models on Ecology and Evolution, Reading, UK. July 2022.', slides: '/Talks/Reading_22.pdf'}
- {name: 'Journées de Probabilités, Orbey, France. June 2022.', slides: 'None'}
- {name: 'Etheridge Group Seminar. Oxford University, UK. July 2021.', slides: '/Talks/Oxford_2021.pdf'}
- {name: 'École de la Chaire MMB. Aussois, France. June 2021.', slides: '/Talks/Aussois_2021.pdf'}

social:
- {icon: 'twitter', link: 'https://twitter.com/NicoZalduendo'}
- {icon: 'instagram', link: 'https://instagram.com/nico.zalduendo'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/nicolás-zalduendo-vidal-007093133/'}

contacts:
- {name: 'Nicolás Zalduendo', title: 'PhD Student', department: 'Applied Mathematics', institution: 'Université de Lorraine', institution_address: 'Institut Elie Cartan de Lorraine (IECL)<br>Université de Lorraine<br>Faculté des Sciences et Technologies<br>Campus Aiguillettes B.P. 70239<br>F-54506 Vandœuvre-lès-Nancy Cedex<br>France', phone: '(000) 000-0000', email: 'zalduend1 at univ-lorraine.fr', office: '126, IECL Building', image: 'assets/img/IECL.jpg'}
