menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Talks', url: '/talks'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

talks:
- {name: 'Workshop on Probability, Ecology and Evolution, Besançon, France. December 2024.', slides: 'None'}
- {name: 'Discrete Ranomness Conference, Créteil, France. December 2023.', slides: 'None'}
- {name: 'Workshop L2 in Probability and Statistics, Metz, France. September 2023.', slides: 'None'}
- {name: '21st INFORMS Applied Probability Society Conference, Nancy, France. June 2023.', slides: 'None'}
- {name: 'Mathematical Models on Ecology and Evolution, Reading, UK. July 2022.', slides: '/Talks/Reading_22.pdf'}
- {name: 'Journées de Probabilités, Orbey, France. June 2022.', slides: 'None'}
- {name: 'Etheridge Group Seminar. Oxford University, UK. July 2021.', slides: '/Talks/Oxford_2021.pdf'}
- {name: 'École de la Chaire MMB. Aussois, France. June 2021.', slides: '/Talks/Aussois_2021.pdf'}

social:
- {icon: 'twitter', link: 'https://twitter.com/NicoZalduendo'}
- {icon: 'instagram', link: 'https://instagram.com/nico.zalduendo'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/nicolás-zalduendo-vidal-007093133/'}

contacts:
- {name: 'Nicolás Zalduendo', title: 'Postdoctoral Researcher', department: 'Applied Mathematics', institution: 'INRAE Occitanie-Montpellier', institution_address: 'INRAE Occitanie-Montpellier (IECL)<br>UMR Mistea<br>2 Place Pierre Viala<br>Bâtiment 21<br>34060 Montpellier cedex 1<br>France', phone: '(000) 000-0000', email: 'nicolas.zalduendo-vidal@inrae.fr', office: '307', image: 'assets/img/Château-La-Gaillarde.jpg'}
